### ISSUE TITLE
Module fails to import properly in Python 3.4

### ISSUE THREAD

**Issue by chrishanretty** [maxlit/powerindex#1]
Running the example from the docs gives the following:

```
    >>> import powerindex as px
    >>> game = px.Game(51,[51,49])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    AttributeError: 'module' object has no attribute 'Game'
```

**Comment by maxlit** [comment]
The module was written for Python 2.7. At the moment there some more important issues than making it compatible with Python 3.x. I'll adjust documentation soon to mention it.

**Comment by maxlit** [comment]
upgraded to python 3.x
