### ISSUE TITLE
Sample Generation and Variable Type Checks

### ISSUE THREAD

**Issue by BradKML** [maxlit/powerindex#7]
There are certain cases where people would wish to estimate the power of a voting block without the context/distribution of other voting blocks. Here below presents the method for generating example data based on three indices: main voting block percentage, party count, and power index (Zipf's Law Distribution).

```python
def sample(main_ratio, count=7, factor=1.0, scale=1000):
  assert(factor >= 0 and isintance(factor, float))
  assert(count > 0 and isintance(factor, int))
  assert(1 > main_ratio > 0)
  others = [1 / (i ** factor) for i in range(1,count+1)]
  others = [sum(others) / (1 - main_ratio) * main_ratio] + others
  return round(sum(a)/2), [round(i/sum(others)*scale) for i in others]
```

**Comment by BradKML** [comment]
As an after-testing note, quota AND weights have to be integers. Unfortunately, the application will not throw such an error.

**Comment by BradKML** [comment]
For testing, find the Pareto Shell of...
- Party Count from 1 to 32
- Power from 1 to 3, in steps of 1/16
- Ratio, from 0 to 1, in steps of 1/32

**Comment by maxlit** [comment]
probably it was the case back then, currently (version 0.2.4), non-integer weights lead to an error (example in bash).
`px -q 4 -w 2 2 2.5`

> usage: px [-h] [-i INDEX] [-q QUOTA] -w WEIGHT [WEIGHT ...]
> px: error: argument -w/--weights: invalid int value: '2.5'

tbh, I don't quite understand the context of generating example data and 'the power of a voting block without the context/distribution of other voting blocks'. If it's still an issue, feel free to provide more context and re-open the issue.
